### ISSUE TITLE
Enhancement Request: support node 0.10

### ISSUE THREAD

**Issue by illegalprime** [bellbind/node-v4l2camera#17]
How difficult would it be to add support for node 0.10?

**Comment by bellbind** [comment]
The [0.4.3](https://github.com/bellbind/node-v4l2camera/releases/tag/0.4.3) is made with node-0.10.x.

You can compare the [current](https://github.com/bellbind/node-v4l2camera/blob/master/v4l2camera.cc) and [0.4.3](https://github.com/bellbind/node-v4l2camera/blob/6e322cd6e366e8df33fc64ff92f8b68e59be8b11/v4l2camera.cc) of `v4l2camera.cc`

It is just an interface code with node.js for the `capture.c` that contains all of controlling v4l2.
The interface code is almost using v8 (or nan/node) API.

For example, `Camera::ControlSet` that includes using this, using arguments, 
returning value, and throwing erros.
The 0.4.3 is:

```c++
  v8::Handle<v8::Value> Camera::ControlSet(const v8::Arguments& args) {
    v8::HandleScope scope;
    if (args.Length() < 2) 
      return throwTypeError("arguments required: id, value");
    uint32_t id = args[0]->Uint32Value();
    int32_t value = args[1]->Int32Value();
    auto thisObj = args.This();
    auto camera = node::ObjectWrap::Unwrap<Camera>(thisObj)->camera;
    bool success = camera_control_set(camera, id, value);
    if (!success) return throwError(camera);
    return scope.Close(thisObj);
  }
```

The current is:

```c++
  NAN_METHOD(Camera::ControlSet) {
    if (info.Length() < 2) {
      Nan::ThrowTypeError("arguments required: id, value");
      return;
    }
    const auto id = info[0]->Uint32Value();
    const auto value = info[1]->Int32Value();
    auto thisObj = info.Holder();
    auto camera = Nan::ObjectWrap::Unwrap<Camera>(thisObj)->camera;
    auto success = bool{camera_control_set(camera, id, value)};
    if (!success) {
      Nan::ThrowError(cameraError(camera));
      return;
    }
    info.GetReturnValue().Set(thisObj);
  }
```

The most incompatibility is widely introduction of `MaybeLocal` and `Maybe` in v8 API.
It is the reason that the nan-2(required node>=4) and nan-1(support node-0.x) become incompatible.

**Comment by illegalprime** [comment]
Thanks, I'll take a look at those.
