### ISSUE TITLE
Duplicated links in the article about node.js native modules programming.

### ISSUE THREAD

**Issue by Dzenly** [bellbind/node-v4l2camera#18]
The page: https://github.com/bellbind/node-v4l2camera/wiki/Node.js-native-module-programming
contains the same two links at the end:

```
https://gist.github.com/bellbind/a68620383e0180b3afc6
https://gist.github.com/bellbind/a68620383e0180b3afc6
```

**Comment by bellbind** [comment]
Thank you. I fixed links of the page.

- Native Module with libuv and Promise: https://gist.github.com/bellbind/b69c3aa266cffe43940c
